name: CI

on:
  push:
    branches:
      - main
    tags: '*'

  pull_request:
    branches:
      - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  ubuntu-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Install Packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y cmake
        sudo apt-get install -y iwyu
        sudo apt-get install -y libgtest-dev

    - name: Configure CMake
      run: |
        cmake --version
        cmake -S . -B build
        ls build

    - name: Build and test
      run: cmake --build-and-test . ./build
