name: CI

on:
  push:
    branches:
      - main
    tags: '*'

  pull_request:
    branches:
      - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build-and-test:
    name: ${{ matrix.os }} - ${{ matrix.arch }} - GTest ${{ matrix.gtest }} - ${{ github.event_name }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        arch: [x64, x86]
        gtest: [system, local]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Install Packages (ubuntu, GoogleTest installed system-wide)
      if: runner.os == 'Linux' && matrix.gtest == 'system'

      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libgtest-dev

    - name: Install Packages (ubuntu, GoogleTest installed locally)
      if: runner.os == 'Linux' && matrix.gtest == 'local'

      run:

    - name: Install Packages (macOS, GoogleTest installed system-wide)
      if: runner.os == 'macOS' && matrix.gtest == 'system'

      run: |
        brew reinstall gcc
        brew install googletest

    - name: Install Packages (macOS, GoogleTest installed locally)
      if: runner.os == 'macOS'

      run: |
        brew reinstall gcc

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build library and tests
      run: cmake --build build --target tests

    - name: Run tests
      run: cmake --build build --target test
