name: CI

on:
  push:
    branches:
      - main
    tags: '*'

  pull_request:
    branches:
      - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build-and-test:
    name: ${{ matrix.os }} - ${{ github.event_name }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        arch: [x64, x86]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Install Packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y cmake
        sudo apt-get install -y iwyu
        sudo apt-get install -y libgtest-dev

    - name: Configure CMake
      run: |
        cmake --version
        cmake -S . -B build
        ls build

    - name: Build library and tests
      run: cmake --build build --target tests

    - name: Run tests
      run: cmake --build build --target test
